const categories = [
  { category: "Any Category", category_id: " " },
  { category: "General Knowledge", category_id: 9 },
  { category: "Entertainment: Books", category_id: 10 },
  { category: "Entertainment: Film", category_id: 11 },
  { category: "Entertainment: Music", category_id: 12 },
  { category: "Entertainment: Musicals & Theatres", category_id: 13 },
  { category: "Entertainment: Television", category_id: 14 },
  { category: "Entertainment: Video Games", category_id: 15 },
  { category: "Entertainment: Board Games", category_id: 16 },
  { category: "Science & Nature", category_id: 17 },
  { category: "Science: Computers", category_id: 18 },
  { category: "Science: Mathematics", category_id: 19 },
  { category: "Mythology", category_id: 20 },
  { category: "Sports", category_id: 21 },
  { category: "Geography", category_id: 22 },
  { category: "History", category_id: 23 },
  { category: "Politics", category_id: 24 },
  { category: "Art", category_id: 25 },
  { category: "Celebrities", category_id: 26 },
  { category: "Animals", category_id: 27 },
  { category: "Vehicles", category_id: 28 },
  { category: "Entertainment: Comics", category_id: 29 },
  { category: "Science: Gadgets", category_id: 30 },
  { category: "Entertainment: Japanese Anime & Manga", category_id: 31 },
  { category: "Entertainment: Cartoon & Animations", category_id: 32 },
];

export default categories;
